import { Core } from './core';

export interface Launch {
  fairings: {
    reused: boolean | null,
    recovery_attempt: boolean | null,
    recovered: boolean | null,
    ships: any[]
  } | null,
  links: {
    patch: {
      small: string,
      large: string,
    },
    reddit: {
      campaign: string | null,
      launch: string | null,
      media: string | null,
      recovery: string | null,
    },
    flickr: {
      small: string[],
      original: string[],
    },
    presskit: string | null,
    webcast: string | null,
    youtube_id: string | null,
    article: string | null,
    wikipedia: string | null,
  },
  static_fire_date_utc: string | null,
  static_fire_date_unix: number | null,
  net: boolean | null,
  window: number | null,
  rocket: string | null,
  success: boolean | null,
  failures: any[],
  details: string | null,
  crew: string[],
  ships: string[],
  capsules: string[],
  payloads: string[],
  launchpad: string | null,
  flight_number: number,
  name: string,
  date_utc: string,
  date_unix: number | null,
  date_local: string | null,
  date_precision: string | null,
  upcoming: boolean | null,
  cores: Core[],
  auto_update: boolean | null,
  tbd: boolean | null,
  launch_library_id: string | null,
  id: string,
}
